name: 'datapulse'
version: '1.0.0'
config-version: 2

profile: 'datapulse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  repeat_snapshot_date: ""   # empty => compute dynamically as max_purchase_date - horizon
  repeat_horizon_days: 180

models:
  datapulse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +schema: gold
