FROM apache/airflow:2.8.0

RUN pip install --no-cache-dir \
    apache-airflow-providers-google==10.13.1 \
    google-cloud-bigquery==3.17.2 \
    google-cloud-storage==2.16.0 \
    dbt-core==1.7.17 \
    dbt-bigquery==1.7.8
